In [5]:
import numpy as np
array_1=np.array([1,2,3,4,5,6])
print(array_1)
print(type(array_1))
print(len(array_1))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
6


In [9]:
import numpy as nsec
class UserInputList:
    def main():
        array_1=[]
        n=int(input("Enter the no. of array elements => "))
        for x in range(0,n):
            y=int(input("Enter the array element -> "))
            array_1.append(y)
        print("Final Array => ",array_1)
        array_1.sort()
        print("Ascending Order => ",array_1)
        array_1.sort(reverse=True)
        print("Descending Order => ",array_1,type(array_1))
        array_1=nsec.array(array_1)
        print(array_1,type(array_1))
UserInputList.main()

Final Array =>  [1, 2, 3]
Ascending Order =>  [1, 2, 3]
Descending Order =>  [3, 2, 1] <class 'list'>
[3 2 1] <class 'numpy.ndarray'>


In [20]:
import numpy as np
import random
xyz=np.random.randint(10,20,10)
print(xyz)


[12 19 12 13 10 17 12 15 12 12]


In [29]:
import numpy as np
array_1=np.array([1,2,3,4,5])
array_2=np.array([[1,2,3],[4,5,6]])
array_3=np.array([[[1,2,3],[4,5,6]],[[10,11,12],[18,19,20]]])
print(array_1.ndim)
print(array_2.ndim)
print(array_3.ndim)
z=np.shape(array_3)
print(z)
print(array_3[1,1,2])



1
2
3
(2, 2, 3)
20


In [4]:
import numpy as np
Rows = int(input("Give the number of rows:"))
Columns = int(input("Give the number of columns:"))

# Initializing the matrix
example_matrix = []

print("Please give the entries row-wise:")

# For user input
for _ in range(Rows):  # This for loop is to arrange rows
    r = []
    for __ in range(Columns):  # This for loop is to arrange columns
        r.append(int(input()))
    example_matrix.append(r)

# PPrintingrinting the matrix given by user
for _ in range(Rows):
    for __ in range(Columns):
        print(example_matrix[_][__], end=" ")
    print()
# print(example_matrix.ndim)
arr_3=np.array(example_matrix)
arr_4=arr_3.reshape(2,2,3)
print("\n\n-------3D ARRAY FINAL--------")
print(arr_4)
print(arr_4.ndim)

Please give the entries row-wise:
2 
3 
4 
5 
6 
7 
8 
9 
10 
11 
12 
13 


-------3D ARRAY FINAL--------
[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]
3


In [5]:
import numpy as np
class ArraySplit:
    def NumpyArray_Split():
        arr_1=[]
        n=int(input("No. of array elements -> "))
        for x in range(0,n):
            y=int(input("Enter array element -> "))
            arr_1.append(y)
        arr_1=np.array(arr_1)
        print("Original Array -> ",arr_1)
        arr_2=np.array_split(arr_1,3)
        print("Split Array -> ",arr_2)
ArraySplit.NumpyArray_Split()

Original Array ->  [ 1  2  3  4  5  6  7  8  6 10]
Split Array ->  [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  6, 10])]
